### ISSUE TITLE
Cannot Send Small Change Amounts

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum-web-wallet#26]
After sending coins where there is a small balance left 0.23, 0.99, 1.01, etc., the wallet is unable to send this value, the CONFIRM button is not activated. Still can’t send after change transaction matures for 501 blocks. Possible to send leaving 0 balance, but a small balance cannot be sent. Repeatable problem as seen on Testnet.

The debug log showed:

```
[2018-12-12T06:03:35.952Z] [ERROR] "restore_key_file_restore_wif_error","Error: Non-base58 character\n    at Object.i [as decode] (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:29:21675)\n    at Object.s [as decode] (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:29:60505)\n    at Object.o [as decode] (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:12:19455)\n    at Function.ECPair.fromWIF (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:37:23569)\n    at Function.value (https://qtumwallet.org/static/js/app.b50892e4130c476813ba.js:1:221558)\n    at Object.l [as restoreFromWif] (https://qtumwallet.org/static/js/app.b50892e4130c476813ba.js:1:112291)\n    at s.inputed (https://qtumwallet.org/static/js/app.b50892e4130c476813ba.js:1:64318)\n    at s.e (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:1:284451)\n    at s.t.$emit (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:6:9184)\n    at s.confirmPassword (https://qtumwallet.org/static/js/app.b50892e4130c476813ba.js:1:261458)"
[2019-01-02T00:47:24.862Z] [ERROR] "send_generate_tx_error","Error: You do not have enough QTUM to send\n    at r (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:6:243894)\n    at Object.i [as buildPubKeyHashTransaction] (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:6:244001)\n    at Function.<anonymous> (https://qtumwallet.org/static/js/app.b50892e4130c476813ba.js:1:220210)\n    at r (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:24:7995)\n    at Generator._invoke (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:24:9040)\n    at Generator.t.(anonymous function) [as next] (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:24:8174)\n    at r (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:29:89470)\n    at https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:29:89618\n    at new Promise (<anonymous>)\n    at new e (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:29:242405)"
[2019-01-05T02:15:19.942Z] [ERROR] "send_generate_tx_error","Error: You do not have enough QTUM to send\n    at r (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:6:243894)\n    at Object.i [as buildPubKeyHashTransaction] (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:6:244001)\n    at Function.<anonymous> (https://qtumwallet.org/static/js/app.b50892e4130c476813ba.js:1:220210)\n    at r (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:24:7995)\n    at Generator._invoke (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:24:9040)\n    at Generator.t.(anonymous function) [as next] (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:24:8174)\n    at r (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:29:89470)\n    at https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:29:89618\n    at new Promise (<anonymous>)\n    at new e (https://qtumwallet.org/static/js/vendor.1956e42f42c7d5cc4f6a.js:29:242405)"
```

![screenhunter 2036](https://user-images.githubusercontent.com/29760787/50729848-f50d1380-110e-11e9-9f19-70f7df96dd12.jpg)
0.23 QTUM balance

![screenhunter 2035](https://user-images.githubusercontent.com/29760787/50729852-08b87a00-110f-11e9-8165-e6013e60a923.jpg)
Balance shown on Explorer

![screenhunter 2037](https://user-images.githubusercontent.com/29760787/50729854-1241e200-110f-11e9-9897-b4e62379e13c.jpg)
Attempting to send, CONFIRM button never becomes active

**Comment by Baiqiang** [comment]
Please fill the amount with the format `0.20` instead of `.20`/

**Comment by qtumweiyu** [comment]
I think the amount should be 0.20
